### ISSUE TITLE
Fix MacOS clipboard tracking

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/clippy#3]
Currently, Mac clipboard tracking doesn't work by default. The user has to apply the instructions at the end of the README https://github.com/AndreasArvidsson/clippy/blob/8a0f16501d30db4839536b196b29d5ce265c5418/README.md#L29-L31

We should figure out a better solution

**Comment by AndreasArvidsson** [comment]
I think we can probably solve this when we package the application?

**Comment by pokey** [comment]
No idea, just figured we should have an issue to track it

**Comment by AndreasArvidsson** [comment]
I might have a solution for this
https://github.com/AndreasArvidsson/clippy/blob/791ed8593c33859d07bbcf55d543448ae47f8f34/prepareAssets.ts#L25-L42

**Comment by AndreasArvidsson** [comment]
Appears to be working
