### ISSUE TITLE
Pinning panel not working on osx.

### ISSUE THREAD

**Issue by GetBitOutdoors** [AndreasArvidsson/clippy#6]
Just updated to latest Clippy. Currently at 0.7.0. And copied userland talon code.
Running osx m1.
Pinning (or sticky behavior) no longer works. I can run pin command and see change panel pin icon. But the window does not stay in front of other apps anymore. If I call "clippy" it can come back up to the top.

**Comment by GetBitOutdoors** [comment]
Nevermind, I see the sticky behavior is now in the settings panel.
![image](https://github.com/user-attachments/assets/0609fef6-d4b8-42c5-95e3-fe3aa07023cc)

**Comment by AndreasArvidsson** [comment]
Before the application was always "always on top", but now that is a setting.
The pinning behavior should be the same.

fyi if you hover over the settings or one of the icons you should get a text describing their behavior.
